### ISSUE TITLE
SSDP headers are case insensitive

### ISSUE THREAD

**Issue by mprobst-irt** [fraunhoferfokus/cordova-plugin-hbbtv#5]
we found an issue with this plugin, when testing DIAL with a number of HbbTV 2 TVs, related to 
how headers are written by a TV in SSDP responses.

The problem occurs with the LOCATION header which is evaluated in

src/android/dial/Dial.java line number 70

UPnP defines SSDP headers as

"The message header fields in a SSDP message shall be formatted according to RFC 2616
clause 4.2. This specifies that each message header field consist of a case-insensitive field
name followed by a colon (":"), followed by the case-sensitive field value. SSDP restricts
allowed field values."

The plugin expects the header's field name to be upper case, ie. LOCATION while also Location is valid. I fixed it locally in android/ssdp/SsdpMessage.java line 60 by converting all header keys to upper case.

**Comment by louaybassbouss** [comment]
Thanks @mprobst-irt for your effort I just merged your PR.
